// <auto-generated />
namespace LastLab.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateProp_UserName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateProp_UserName));
        
        string IMigrationMetadata.Id
        {
            get { return "202103251713333_updateProp_UserName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
