// <auto-generated />
namespace LastLab.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_instructor_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_instructor_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202104042011262_update_instructor_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
