// <auto-generated />
namespace LastLab.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updating_student : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updating_student));
        
        string IMigrationMetadata.Id
        {
            get { return "202103272132536_updating_student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
